server:
  port: 8081

spring:
  application:
    name: stock-service
  kafka:
    bootstrap-servers: localhost:19092
    consumer:
      group-id: stock-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: nl.craftsmen.asyncapidemo.stockservice.dto
        spring.json.value.default.type: nl.craftsmen.asyncapidemo.stockservice.dto.OrderCreatedEvent
        spring.json.use.type.headers: false

app:
  kafka:
    topic:
      order-created: orders.created
