server:
  port: 8080

spring:
  application:
    name: order-service
  cloud:
    stream:
      bindings:
        orderCreated-out-0:
          destination: orders.created
      kafka:
        binder:
          brokers: localhost:19092
